## TODO: Modularize the gitlab yaml to reuse templates

## Define the stages & order of execution

stages:
  - CLUSTER-SETUP
  - PROVIDER-INFRA-SETUP
  - DIRECTOR-SANITY-CHECK
  - DIRECTOR-FUNCTIONALITY-CHECK
  - CLUSTER-CLEANUP

## Setup the kubernetes cluster

cluster-create:
  image: atulabhi/kops:v8
  stage: CLUSTER-SETUP
  script: 
    - chmod 755 ./stages/1-cluster-setup/gcp
    - ./stages/1-cluster-setup/gcp
  artifacts:
    when: always
    paths:
      - .kube/

## Deploy DOP

director-deploy:
  image: atulabhi/kops:v8
  stage: PROVIDER-INFRA-SETUP
  dependencies:
    - cluster-create
  script: 
   - chmod 755 ./stages/2-provider-infra-setup/infra-setup
   - ./stages/2-provider-infra-setup/infra-setup
  artifacts:
    paths:
      - .kube/

maya-io-server-check:
  image: atulabhi/kops:v8
  stage: DIRECTOR-SANITY-CHECK
  dependencies:
    - director-deploy
  script: 
   - chmod 755 ./stages/3-director-sanity-check/maya-io-server-check
   - ./stages/3-director-sanity-check/maya-io-server-check
  artifacts:
    paths:
      - .kube/

maya-ui-check:
  image: atulabhi/kops:v8
  stage: DIRECTOR-SANITY-CHECK
  dependencies:
    - director-deploy
  script: 
    - chmod 755 ./stages/3-director-sanity-check/maya-ui-check
    - ./stages/3-director-sanity-check/maya-ui-check
  artifacts:
    paths:
      - .kube/

dmaas-check:
  image: atulabhi/kops:v8
  stage: DIRECTOR-FUNCTIONALITY-CHECK
  dependencies:
    - director-deploy
  script: 
   - chmod 755 ./stages/4-director-functionality-check/dmaas-check
   - ./stages/4-director-functionality-check/dmaas-check
  artifacts:
    paths:
      - .kube/

cluster-cleanup:
  when: always
  image: atulabhi/kops:v8
  dependencies:
    - cluster-create
  stage: CLUSTER-CLEANUP
  script: 
    - chmod 755 ./stages/5-cluster-cleanup/cluster-cleanup
    - ./stages/5-cluster-cleanup/cluster-cleanup